### ISSUE TITLE
Only color theme works

### ISSUE THREAD

**Issue by KristianOde** [ekaaty/vinyl-theme#1]
After following the install instructions, only the color scheme appears in settings but no application style, window decoration etc. Not sure if I'm missing something or if it's not implemented yet. The installation logs tells me that a bunch of files are being created in various folders but they don't appear to do anything. I can run `vinyl-settings6` in the terminal where a window with no functionality pop ups and the terminal says `kf.coreaddons: "Could not find plugin kstyle_config/vinylstyleconfig"
kf.coreaddons: "Could not find plugin kstyle_config/vinylstyleconfig"
kf.coreaddons: "Could not find plugin org.kde.kdecoration2.kcm/kcm_vinyldecoration.so"
kf.coreaddons: "Could not find plugin org.kde.kdecoration2.kcm/kcm_vinyldecoration.so"`
I'm on Fedora 40.

**Comment by christiantosta** [comment]
Seems that you missed some detail in the build process. Only colors, decorations and application style is implemented at this point, but it's usable. You can grab the Fedora's 40 package here: [Vinyl packages for Fedora 40](https://download.copr.fedorainfracloud.org/results/ekaaty/kde-extras/fedora-40-x86_64/07195082-vinyl-theme/).

**Comment by pyrareae** [comment]
To get the application style to show up on Fedora I had to change the installation dir to `/usr`. Whereas the instructions used `/usr/local`.

```
export PREFIX=/usr
export DESTDIR=/

cd vinyl-theme
cmake --install build --prefix ${PREFIX}
```

**Comment by christiantosta** [comment]
Fixed build instructions on README.md.
