### ISSUE TITLE
Opensuse tumbleweed build error

### ISSUE THREAD

**Issue by eleaf33** [ekaaty/vinyl-theme#7]
I have installed all the required packages, but I am getting an error
cmake -S . -B build
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Could not set up the appstream test. appstreamcli is missing.
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found XKB: /usr/lib64/libxkbcommon.so (found suitable version "1.7.0", minimum required is "0.5.0")
-- Found WrapVulkanHeaders: /usr/include
-- Found KF6CoreAddons: /usr/lib64/cmake/KF6CoreAddons/KF6CoreAddonsConfig.cmake (found version "6.7.0")
-- Found KF6ColorScheme: /usr/lib64/cmake/KF6ColorScheme/KF6ColorSchemeConfig.cmake (found version "6.7.0")
-- Found KF6Config: /usr/lib64/cmake/KF6Config/KF6ConfigConfig.cmake (found version "6.7.0")
-- Found KF6GuiAddons: /usr/lib64/cmake/KF6GuiAddons/KF6GuiAddonsConfig.cmake (found version "6.7.0")
-- Found Gettext: /usr/bin/msgmerge (found version "0.22.5")
-- Found KF6I18n: /usr/lib64/cmake/KF6I18n/KF6I18nConfig.cmake (found version "6.7.0")
-- Found KF6IconThemes: /usr/lib64/cmake/KF6IconThemes/KF6IconThemesConfig.cmake (found version "6.7.0")
-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found KF6WindowSystem: /usr/lib64/cmake/KF6WindowSystem/KF6WindowSystemConfig.cmake (found version "6.7.0")
-- Found KF6: success (found suitable version "6.7.0", minimum required is "6.5.0") found components: CoreAddons ColorScheme Config GuiAddons I18n IconThemes WindowSystem
-- Found KF6DocTools: /usr/lib64/cmake/KF6DocTools/KF6DocToolsConfig.cmake (found version "6.7.0")
-- Found KF6Package: /usr/lib64/cmake/KF6Package/KF6PackageConfig.cmake (found version "6.7.0")
-- Found KF6: success (found suitable version "6.7.0", minimum required is "6.5.0") found components: DocTools Package
CMake Error at CMakeLists.txt:180 (find_package):
  By not providing "FindPlasma.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Plasma", but
  CMake did not find one.

  Could not find a package configuration file provided by "Plasma" (requested
  version 6.1.0) with any of the following names:

    PlasmaConfig.cmake
    plasma-config.cmake

  Add the installation prefix of "Plasma" to CMAKE_PREFIX_PATH or set
  "Plasma_DIR" to a directory containing one of the above files.  If "Plasma"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:215 (build_Qt6)

-- Configuring incomplete, errors occurred!

**Comment by christiantosta** [comment]
Seems OpenSUSE doesn't provides 'cmake(Plasma)'. Instead it provides 'cmake(KF6Package)'. 

So, you need to replace on the CMakefile.txt where:
find_package(Plasma ${PLASMA_MIN_VERSION} REQUIRED)

To:
find_package(KF6Package ${PLASMA_MIN_VERSION} REQUIRED)

And install the package libplasma6-devel.

**Comment by christiantosta** [comment]
Simple install the 'libplasma6-devel' package on your Opensuse.
